### ISSUE TITLE
Doesn't appear in Extensions

### ISSUE THREAD

**Issue by normand1** [Bouke/SwiftInitializerGenerator#11]
Followed instructions but nothing appears in System Preferences -> Extensions

Any Clues? Thanks

OS Version: 10.11.6 (15G1217)
Xcode Version: 8.2.1 (8C1002)

**Comment by Bouke** [comment]
Can you try running the following command and then restarting your Mac?

    sudo /usr/libexec/xpccachectl

Then proceed with step 8 (running the app).
