### ISSUE TITLE
Wrong example in the readme

### ISSUE THREAD

**Issue by FlorianBasso** [Bouke/SwiftInitializerGenerator#2]
`struct MyStruct {
    public var a: String
    public var b: Int
    public init(a: String, b: String) {
        self.a = a
        self.b = b
    }
}
 `

should be 
`struct MyStruct {
    public var a: String
    public var b: Int
    public init(a: String, b: Int) {
        self.a = a
        self.b = b
    }
}
 `

b is an Int not a String

**Comment by Bouke** [comment]
Ah yes, an oversight. Thanks!
