### ISSUE TITLE
xcode error

### ISSUE THREAD

**Issue by zhuyuping** [Bouke/SwiftInitializerGenerator#24]
[
![WX20200427-103755](https://user-images.githubusercontent.com/16640301/80328867-35981f80-8873-11ea-8b78-30d574f72437.png)
](url)

**Comment by zhuyuping** [comment]
Xcode Version 11.3.1 (11C504)

**Comment by Bouke** [comment]
Without any further information there’s little anyone can do about this.

**Comment by zhuyuping** [comment]
![WX20200427-103755](https://user-images.githubusercontent.com/16640301/80337592-d6470900-888c-11ea-8528-0021576ce94d.png)

**Comment by zhuyuping** [comment]
"The operation could not be completed.(Generate_Swift_Initalizer.SIGError error 3.)"
There was an error when I used it. In the top of Xcode edit view

can you see the image I upload?
