### ISSUE TITLE
Cannot Initialize `private` properties.

### ISSUE THREAD

**Issue by linebounce** [Bouke/SwiftInitializerGenerator#3]
The extension works great! However, when you try to initialize private properties, you get the following error:

"The operation couldn't be completed. (Generate_Swift_Initializer.SourceEditorCommand.Error error 3)"

**Comment by linebounce** [comment]
After looking at the source code, it seems that the error is coming from this line at the beginning of the `perform` function.

"guard invocation.buffer.contentUTI == "public.swift-source" else {
            return completionHandler(Error.notSwiftLanguage)
        }"

**Comment by Bouke** [comment]
At the moment, only public or internal properties are supported. See also the last line of the README:

    It will only parse attributes defined like (public|internal) (var|let) NAME: TYPE.

However it should be rather easy to add other access modifiers.

**Comment by linebounce** [comment]
Thanks for the quick response! Do you have plans to add this functionality?

**Comment by Bouke** [comment]
I've made some changes in 4c73493d529511dcc32fafb2f57a07a04b2afe47. Feel free to send in additional patches if the extension comes in handy.
