### ISSUE TITLE
"Embedded binary is not signed with the same certificate as the parent app" error when building

### ISSUE THREAD

**Issue by NachoSoto** [Bouke/SwiftInitializerGenerator#5]
_Disclaimer: I'm 99.99% sure this issue has nothing to do with this repo, and it's just an(other) Xcode bug, I just figured I'd open this to see if other people run into the same thing_.

I was super excited to use this extension, but I'm getting the following error:
<img width="911" alt="screen shot 2016-10-05 at 5 17 07 pm" src="https://cloud.githubusercontent.com/assets/685609/19136304/5607855c-8b20-11e6-8b43-f685263a55ed.png">

I do have the same team in both targets:
<img width="344" alt="screen shot 2016-10-05 at 5 23 00 pm" src="https://cloud.githubusercontent.com/assets/685609/19136309/6962c36e-8b20-11e6-8fb3-e4186c070249.png">
<img width="341" alt="screen shot 2016-10-05 at 5 23 06 pm" src="https://cloud.githubusercontent.com/assets/685609/19136310/697bf438-8b20-11e6-8303-69cedb89fe5f.png">

But of course Xcode is doing something wrong... or maybe I am? I hadn't used automatic signing yet, so maybe I'm doing something wrong.

_Note: I'm on Xcode 8.0_

**Comment by Bouke** [comment]
See the resolution in the linked issue. I've reverted the Copy Files phase, which should resolve this.
