### ISSUE TITLE
"This target might include its own product" error when archiving

### ISSUE THREAD

**Issue by NachoSoto** [Bouke/SwiftInitializerGenerator#6]
I get this error whenever I archive (using `Xcode 8`). If I just _build_, I get #5:

<img width="753" alt="screen shot 2016-10-05 at 5 28 03 pm" src="https://cloud.githubusercontent.com/assets/685609/19136382/1769f838-8b21-11e6-8db7-e2f82f487a41.png">

I tried disabling "Find Implicit Dependencies" in the scheme, and removing the explicit target dependency in the app target, but nothing helped :/

**Comment by broadwaylamb** [comment]
Go to **Build Phases** for the target "SwiftInitializerGenerator" and remove the **Copy Files** phase.

**Comment by rcritz** [comment]
I had the same issue. Deleting the **Copy Files** stage got it to build and archive. However, following the remaining steps in the README still goes get me a functioning extension. It does not appear in the **Editor** menu.

**Comment by Bouke** [comment]
I've reverted the Copy Files phase, thanks. @rcritz can you try once again? And maybe try and check if there's something logged in the Console app? If it still doesn't work, please open a new issue, as it is not related to the one discussed here.

**Comment by NachoSoto** [comment]
> I had the same issue. Deleting the Copy Files stage got it to build and archive. However, following the remaining steps in the README still goes get me a functioning extension. It does not appear in the Editor menu.

Same here: I managed to build, archive, and install the extension as described in the `README`. However, it's still not showing up on the `Editor` menu in `Xcode`, despite multiple attempts, restarting Xcode, etc.

**Comment by JimiSmith** [comment]
@NachoSoto @rcritz I had to go to System Preferences -> Extensions -> Xcode Source Editor and enable the extension before it showed up

**Comment by anoirnab** [comment]
I have the same problem can you mack a video for this problem please guys help me
