### ISSUE TITLE
Does not show option in the Editor menu

### ISSUE THREAD

**Issue by ed-mejia** [Bouke/SwiftInitializerGenerator#7]
As mentioned in #6

Following README instructions it's still not showing up on the Editor menu in Xcode, despite multiple attempts, restarting Xcode, etc.

**Comment by JimiSmith** [comment]
@ed-mejia  I had to go to System Preferences -> Extensions -> Xcode Source Editor and enable the extension before it showed up

Perhaps this should be added to the readme

**Comment by Bouke** [comment]
Thanks, I've mentioned this in the README, see 34bd934b83bf4522d7072faa71dade9a5f5cd0e6. @ed-mejia can you confirm that this solves your issue?

**Comment by ed-mejia** [comment]
Does this require Mac OS Sierra? I'm on El Capital and I'm unable to see any option for Xcode in the system preferences, extensions, etc 😩

**Comment by Bouke** [comment]
It should work on El Capitan, but might require additional steps:

* ``sudo /usr/libexec/xpccachectl``
* reboot your mac
* sign the host application (per README)
* run the app (per README)
* wait a little while before launching Xcode

Can you confirm that the above works for you?

**Comment by ed-mejia** [comment]
I tried at the office and didn't work, I will try later at home and check it again.
