### ISSUE TITLE
Ignore Empty Lines and Comments

### ISSUE THREAD

**Issue by mohamede1945** [Bouke/SwiftInitializerGenerator#9]
Currently, if there are empty lines between the properties or comments, the extension doesn't work and crashes.

**Comment by Bouke** [comment]
That's currently how it works, yes. Feel free to provide a patch that does handle such scenarios though. The extension doesn't crash however, it provides an `Error` to the `completionHandler` (which in Xcode probably incorrectly shows up as a crash).

**Comment by rjoudrey** [comment]
See https://github.com/rjoudrey/swift-init-generator

**Comment by Bouke** [comment]
Fixed in 8ad07889eedc79499067a124c11468e5416c74ea.
